apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blocky-doh
  namespace: internal-dns
  labels:
    backupWeekly: "true"
    backupDaily: "true"
    app.kubernetes.io/part-of: blocky
spec:
  secretName: tls-blocky
  secretTemplate:
    labels:
      backupWeekly: "true"
      backupDaily: "true"
      app.kubernetes.io/part-of: blocky
  issuerRef:
    name: ${certificate_cluster_issuer:=letsencrypt-production}
    kind: ClusterIssuer
  dnsNames:
  - ns1.${domain_wahoo_li:=wahoo.li}
  - ns2.${domain_absolutist_it:=absolutist.it}
  - ns.${domain_wahoo_li:=wahoo.li}
  - ns.${domain_absolutist_it:=absolutist.it}
  - dns.${domain_wahoo_li:=wahoo.li}
  - dns.${domain_absolutist_it:=absolutist.it}
