log:
  level: info
  job_level: info

runner:
  file: /data/.runner
  capacity: 1
  envs:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: /certs/client
  env_file: .env
  timeout: 3h
  shutdown_timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  report_interval: 1s
  labels:
  - "linux-arm64:docker://zot.registry.svc:5000/ghcr/catthehacker/ubuntu:act-24.04"
  - "linux:docker://zot.registry.svc:5000/ghcr/catthehacker/ubuntu:act-24.04"
  - "java:docker://zot.registry.svc:5000/ghcr/catthehacker/ubuntu:java-tools-24.04"
  - "dotnet:docker://zot.registry.svc:5000/ghcr/catthehacker/ubuntu:dotnet-24.04"
  - "go:docker://zot.registry.svc:5000/ghcr/catthehacker/ubuntu:go-24.04"
  - "rust:docker://zot.registry.svc:5000/ghcr/catthehacker/ubuntu:rust-24.04"
  - "js:docker://zot.registry.svc:5000/ghcr/catthehacker/ubuntu:js-24.04"

cache:
  enabled: true
  dir: ""
  host: ""
  port: 0
  proxy_port: 0
  external_server: ""
  secret: ""
  actions_cache_url_override: ""

container:
  network: host
  enable_ipv6: false
  privileged: false
  options: -v /certs/client:/certs/client -v /root/.docker/config.json:/root/.docker/config.json
  workdir_parent:
  valid_volumes:
  - /certs/client
  - /root/.docker/config.json
  docker_host: "-"
  force_pull: false
  force_rebuild: false

host:
  workdir_parent:
