apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: forgejo-runner
  namespace: forgejo-runners
spec:
  maxReplicaCount: 8
  jobTargetRef:
    template:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: forgejo-runner
                topologyKey: kubernetes.io/hostname
