apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-logging
  namespace: flux-system
spec:
  interval: 5m0s
  prune: false
  dependsOn:
  - name: infrastructure-platform
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/logging/tpi-1
  healthChecks:
  - apiVersion: apps/v1
    kind: DaemonSet
    name: vector-agent
    namespace: logging
  - apiVersion: apps/v1
    kind: Deployment
    name: vector-global-write
    namespace: logging
  - apiVersion: apps/v1
    kind: Deployment
    name: vector-lb-tpi
    namespace: logging
  - apiVersion: apps/v1
    kind: Deployment
    name: vmauth-read-proxy
    namespace: logging
  - apiVersion: apps/v1
    kind: StatefulSet
    name: vlogs-short-term-tpi-1
    namespace: logging
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-infrastructure-vars
      optional: false
    - kind: Secret
      name: cluster-vars
      optional: true
