apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: internal-dns
  namespace: flux-system
spec:
  interval: 5m0s
  prune: false
  dependsOn:
  - name: infrastructure
  - name: infrastructure-depends
  - name: monitoring
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: unbound
    namespace: internal-dns
  - apiVersion: apps/v1
    kind: Deployment
    name: blocky
    namespace: internal-dns
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/tpi-1/internal-dns
  postBuild:
    substituteFrom:
    - kind: Secret
      name: dns-vars
      optional: false
    - kind: Secret
      name: cluster-vars
      optional: true
