apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: wyoming-whisper
  namespace: homeassistant-assist
spec:
  predictor:
    volumes:
    - name: models
      persistentVolumeClaim:
        claimName: wyoming-whisper-models
