apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-system--envoy-gateway
  namespace: flux-system
spec:
  releaseName: envoy-gateway
  interval: 10m
  chart:
    spec:
      version: "v1.7.1"
  valuesFrom:
  - kind: ConfigMap
    name: envoy-gateway-values
    valuesKey: values-base.yaml
  - kind: ConfigMap
    name: envoy-gateway-values
    valuesKey: values.yaml
  - kind: ConfigMap
    name: envoy-gateway-values
    valuesKey: values-extra.yaml
    optional: true
