apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/kserve
patches:
- path: helmrelease-crd.yaml
  target:
    kind: HelmRelease
    name: base-kserve-crd
  options:
    allowNameChange: true
- path: helmrelease.yaml
  target:
    kind: HelmRelease
    name: base-kserve
  options:
    allowNameChange: true
configMapGenerator:
- name: kserve-values
  namespace: flux-system
  behavior: merge
  files:
  - values.yaml=values.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
configurations:
- ../../../.config/valuesFrom.yaml
