apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: speaches
  namespace: homeassistant-assist
  labels:
    networking.knative.dev/visibility: cluster-local
  annotations:
    autoscaling.knative.dev/scale-down-delay: "10m"
    autoscaling.knative.dev/window: "60s"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    scaleTarget: 1
    scaleMetric: concurrency
    timeout: 600
    runtimeClassName: nvidia
    model:
      modelFormat:
        name: whisper
      runtime: speaches-cuda
      env:
      - name: WHISPER__MODEL
        value: Systran/faster-whisper-medium
      - name: WHISPER__COMPUTE_TYPE
        value: int8_float16
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 4Gi
