apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: wyoming-whisper-gpu
  namespace: homeassistant-assist
spec:
  predictor:
    volumes:
    - name: config
      persistentVolumeClaim:
        claimName: wyoming-whisper-gpu-models
