apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/wyoming-whisper-gpu
- pvc.yaml
- tcproute.yaml
patches:
- path: inferenceservice.yaml
  target:
    kind: InferenceService
    name: wyoming-whisper-gpu
- path: volumemounts-patch.yaml
  target:
    kind: InferenceService
    name: wyoming-whisper-gpu
