apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-gpu-models
  namespace: homeassistant-assist
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: topolvm-fast
  resources:
    requests:
      storage: 5Gi
