apiVersion: v1
kind: Service
metadata:
  name: flareproxy
  namespace: default
  labels:
    app.kubernetes.io/name: flareproxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: flareproxy
