apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
  namespace: homeassistant-assist
  labels:
    app.kubernetes.io/name: wyoming-whisper
spec:
  type: ClusterIP
  ports:
  - name: wyoming
    port: 10300
    targetPort: wyoming
    protocol: TCP
  selector:
    serving.kserve.io/inferenceservice: wyoming-whisper
