apiVersion: v1
kind: Service
metadata:
  name: wyoming-piper
  namespace: homeassistant-assist
  labels:
    app.kubernetes.io/name: wyoming-piper
spec:
  type: ClusterIP
  ports:
  - name: wyoming
    port: 10200
    targetPort: wyoming
    protocol: TCP
  selector:
    serving.kserve.io/inferenceservice: wyoming-piper
