apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: vps-haproxy
  namespace: monitoring
spec:
  jobName: haproxy
  targetEndpoints:
  - targets:
    - 172.16.3.1:8405
    labels:
      instance: gw01
      source: vps
    interval: 30s
    path: /metrics
  - targets:
    - 172.16.3.2:8405
    labels:
      instance: gw02
      source: vps
    interval: 30s
    path: /metrics
  - targets:
    - 172.16.3.3:8405
    labels:
      instance: gw03
      source: vps
    interval: 30s
    path: /metrics
