apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/kyverno-policies
- policyexception-infrastructure.yaml
- policyexception-root-by-design.yaml
- policyexception-forgejo-runner.yaml
