apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-helmrelease-overrides
  namespace: flux-system
data:
  values.yaml: |
    server:
      controllers:
        main:
          pod:
            runtimeClassName: ""
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
