apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    kind: Service
    name: vector-lb-tpi
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: vector-lb-tpi
