apiVersion: v1
kind: Secret
metadata:
  name: authentik-ldap-outpost-probe
  namespace: authentik
  labels:
    velero.io/exclude-from-backup: "true"
stringData:
  password: ${authentik_jellyfin_bind_user_password}
