image:
  tag: "4.53.5" # {"$imagepolicy": "flux-system:ombi:tag"}
initContainers:
  copy-configuration:
    image: ghcr.io/wahooli/docker/envsubst:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: database_user
      valueFrom:
        secretKeyRef:
          key: database_user
          name: ${ombi_app_secret_name}
    - name: database_password
      valueFrom:
        secretKeyRef:
          key: mariadb-password
          name: ${ombi_app_secret_name}
    volumeMounts:
    - mountPath: /dest
      name: config
    - mountPath: /src
      name: ombi-config
dnsConfig:
  options:
  - name: ndots
    value: "1"
  - name: edns0
persistence:
  config:
    enabled: true
    mount:
    - path: /config
    spec:
      emptyDir: {}
      # jsonConfig:
      #   name: ombi-config
      #   enabled: true
      #   spec:
      #     useFromChart: false
      #     configMap:
      #       name: ombi-database-json
service:
  main:
    annotations:
      service.cilium.io/global: "true"
      service.cilium.io/affinity: "local"
      service.cilium.io/global-sync-endpoint-slices: "true"
ingress:
  main:
    enabled: false
