apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- llama-cpp-cuda.yaml
- imagerepository.yaml
- imagepolicy.yaml
images:
- name: ghcr.io/ggml-org/llama.cpp
  newTag: server-cuda # {"$imagepolicy": "flux-system:llama-cpp-cuda:tag"}
