apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/kserve-runtimes/llama-cpp-cpu
- ../../../base/kserve-runtimes/llama-cpp-cuda
- imagerepository.yaml
- imagepolicy.yaml
