apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: static-backend
  namespace: infrastructure
  annotations:
    external-dns.alpha.kubernetes.io/target: gw.${domain_wahoo_li:=wahoo.li}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  parentRefs:
  - name: envoy-gw
    namespace: envoy-gateway-system
    sectionName: wahooli-https
  hostnames:
  - "static.${domain_wahoo_li:=wahoo.li}"
  rules:
  - backendRefs:
    - name: default-backend
      port: 80
