apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- shared
- imagerepositories
- vector-agent
- vector-global-write
- vector-lb
- vlogs-long-term.yaml
- vlogs-short-term.yaml
- vlsingle-long-term.yaml
- vlsingle-short-term.yaml
- vmauth.read-proxy.yaml
