apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs--seaweedfs
  namespace: flux-system
spec:
  values:
    filer:
      persistence:
        s3Config:
          name: s3-config
          enabled: true
          spec:
            useFromChart: false
            configMap:
              name: seaweedfs-s3-config
  dependsOn:
  - name: cert-manager--cert-manager
    namespace: flux-system
  targetNamespace: seaweedfs
  releaseName: seaweedfs
  valuesFrom:
  - kind: ConfigMap
    name: seaweedfs-values
    valuesKey: values-base.yaml
  - kind: ConfigMap
    name: seaweedfs-values
    valuesKey: values-shared.yaml
  - kind: ConfigMap
    name: seaweedfs-values
    optional: true
    valuesKey: values.yaml
  - kind: ConfigMap
    name: seaweedfs-helmrelease-overrides
    optional: true
    valuesKey: values.yaml
