apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/seaweedfs
- namespace.yaml
- imagepolicy.yaml
- backend-filer.yaml
- httproute-filer.yaml
patches:
- path: helmrelease.yaml
  target:
    kind: HelmRelease
  options:
    allowNameChange: true
configMapGenerator:
- name: seaweedfs-s3-config
  namespace: flux-system
  options:
    labels:
      velero.io/exclude-from-backup: "true"
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "seaweedfs"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "seaweedfs"
  files:
  - s3.json=s3.json
- name: seaweedfs-values
  namespace: flux-system
  behavior: merge
  files:
  - values-shared.yaml=values-shared.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
configurations:
- ../../../.config/valuesFrom.yaml
- kustomizeconfig.yaml
