image:
  tag: "v1.7.6" # {"$imagepolicy": "flux-system:crowdsec:tag"}
agent:
  acquisition:
  - namespace: envoy-gateway-system
    podName: envoy-envoy-gateway-system-envoy-gw-*
    program: envoy-gateway
    poll_without_inotify: false
  - namespace: authentik
    podName: authentik-server-*
    program: authentik
    poll_without_inotify: false
  - namespace: default
    podName: mc-router-*
    program: mc-router
    poll_without_inotify: false
