apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: global-write
  namespace: monitoring
spec:
  port: "8427"
  serviceSpec:
    useAsDefault: true
    spec:
      type: ClusterIP
    metadata:
      annotations:
        service.cilium.io/global: "true"
        service.cilium.io/shared: "true"
        service.cilium.io/affinity: "local"
        service.cilium.io/global-sync-endpoint-slices: "true"
  unauthorizedUserAccessSpec:
    url_map:
    - src_paths:
      - "/api/v1/write"
      - "/prometheus/api/v1/write"
      - "/write"
      - "/api/v1/import"
      - "/api/v1/import/.+"
      load_balancing_policy: first_available
      retry_status_codes:
      - 502
      - 503
      - 504
      url_prefix:
      - http://vmagent-tpi-1.monitoring.svc.cluster.local.:8429
      - http://vmagent-nas.monitoring.svc.cluster.local.:8429
