apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: forgejo-runner-restrict
  namespace: forgejo-runners
spec:
  endpointSelector:
    matchLabels:
      app: forgejo-runner
  egress:
  # Allow DNS
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
  # Allow Forgejo
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: forgejo
    toPorts:
    - ports:
      - port: "3000"
        protocol: TCP
  # Allow Forgejo via gateway (git.wahoo.li)
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: envoy-gateway-system
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "8443"
        protocol: TCP
  # Allow Zot registry
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: registry
    toPorts:
    - ports:
      - port: "5000"
        protocol: TCP
