apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: forgejo-runner-creds
  namespace: forgejo-runners
spec:
  secretTargetRef:
  - parameter: token
    name: forgejo-runner-token
    key: token
