apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/blocky
- blocky-nas.yaml
- httproute.yaml
configMapGenerator:
- name: blocky-values
  namespace: flux-system
  behavior: merge
  files:
  - values-extra.yaml=values-extra.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
configurations:
- ../../../.config/valuesFrom.yaml
