useLegacy: false
image:
  pullPolicy: IfNotPresent

scheduler:
  enabled: true
  type: daemonset

lvmd:
  managed: true

controller:
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

storageClasses: []

podSecurityPolicy:
  create: false

cert-manager:
  enabled: false

priorityClass:
  enabled: true
  name: topolvm
  value: 1000000

snapshot:
  enabled: false
securityContext:
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000
resources:
  topolvm_controller:
    requests:
      memory: 64Mi
    limits:
      memory: 96Mi
  csi_provisioner:
    requests:
      memory: 64Mi
    limits:
      memory: 96Mi
  csi_resizer:
    requests:
      memory: 96Mi
    limits:
      memory: 160Mi
  lvmd:
    requests:
      memory: 96Mi
    limits:
      memory: 160Mi
  topolvm_node:
    requests:
      memory: 64Mi
    limits:
      memory: 96Mi
  csi_registrar:
    requests:
      memory: 32Mi
    limits:
      memory: 64Mi
  topolvm_scheduler:
    requests:
      memory: 48Mi
    limits:
      memory: 96Mi
  liveness_probe:
    requests:
      memory: 32Mi
    limits:
      memory: 64Mi
