apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/assist-llm-gpu
- pvc.yaml
images:
- name: ollama/ollama
  newTag: 0.21.2 # {"$imagepolicy": "flux-system:assist-llm-gpu:tag"}
patches:
- path: inferenceservice.yaml
  target:
    kind: InferenceService
  options:
    allowNameChange: true
- path: volumemounts-patch.yaml
  target:
    kind: InferenceService
    name: assist-llm-gpu
