apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assist-llm-gpu-models
  namespace: homeassistant-assist
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: topolvm-fast
  resources:
    requests:
      storage: 10Gi
