apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../shared/authentik/redis
configMapGenerator:
- name: authentik-redis-values
  namespace: flux-system
  behavior: merge
  files:
  - values.yaml=values.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
