apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry--zot
  namespace: flux-system
spec:
  interval: 10m
  releaseName: zot
  targetNamespace: registry
  chart:
    spec:
      version: "0.1.104"
  values:
    extraVolumes:
    - name: zot-config
      configMap:
        name: zot-config
  valuesFrom:
  - kind: ConfigMap
    name: zot-values
    valuesKey: values-base.yaml
  - kind: ConfigMap
    name: zot-values
    valuesKey: values.yaml
    optional: true
  - kind: ConfigMap
    name: zot-values
    valuesKey: values-extra.yaml
    optional: true
