apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/zot
- imagepolicy.yaml
- httproute-private.yaml
patches:
- path: helmrelease.yaml
  target:
    kind: HelmRelease
  options:
    allowNameChange: true
- path: namespace.yaml
  target:
    kind: Namespace
    name: registry
configMapGenerator:
- name: zot-values
  namespace: flux-system
  behavior: merge
  files:
  - values.yaml=values.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
- name: zot-config
  namespace: flux-system
  files:
  - config.json=config.json
  options:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "registry"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "registry"
configurations:
- ../../../.config/valuesFrom.yaml
- configMapRef.yaml
