image:
  tag: v2.1.15 # {"$imagepolicy": "flux-system:zot:tag"}

persistence: true
pvc:
  create: true
  accessModes:
  - ReadWriteOnce
  storage: 10Gi

mountSecret: true
secretFiles:
  htpasswd: |
    nologin:$2y$05$vmiurPmJvHylk78HHFWuruFFVePlit9rZWGA/FbZfTEmNRneGJtha

externalSecrets:
- secretName: zot-credentials
  mountPath: /etc/zot/credentials

extraVolumeMounts:
- name: zot-config
  mountPath: /etc/zot/config.json
  subPath: config.json
