apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- vmnodescrape/cadvisor.yaml
- vmnodescrape/kubelet.yaml
- vmnodescrape/probes.yaml
- vmnodescrape/resources.yaml
- vmpodscrape/cert-manager.yaml
- vmpodscrape/fluxcd.yaml
- vmpodscrape/node-exporter.yaml
- vmpodscrape/topolvm.yaml
- vmservicescrape/authentik.yaml
- vmservicescrape/ingress-nginx.yaml
- vmservicescrape/kube-dns.yaml
- vmservicescrape/kube-state-metrics.yaml
- vmservicescrape/victoria-metrics-operator.yaml
