apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- vmnodescrape/cadvisor.yaml
- vmnodescrape/kubelet.yaml
- vmnodescrape/probes.yaml
- vmnodescrape/resources.yaml
- vmpodscrape/cert-manager.yaml
- vmpodscrape/fluxcd.yaml
- vmpodscrape/node-exporter.yaml
- vmpodscrape/topolvm.yaml
- vmpodscrape/envoy-gateway-proxy.yaml
- vmservicescrape/authentik.yaml
- vmservicescrape/envoy-gateway.yaml
- vmservicescrape/kube-dns.yaml
- vmservicescrape/kube-state-metrics.yaml
- vmservicescrape/velero.yaml
- vmservicescrape/victoria-metrics-operator.yaml
- vmstaticscrape/vps-node-exporter.yaml
- vmstaticscrape/vps-haproxy.yaml
- vmstaticscrape/vps-cert-metrics.yaml
