apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: llama-cpp-cpu
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: llama-cpp-cpu
  filterTags:
    pattern: '^server-b(?P<build>\d+)$'
    extract: '$build'
  policy:
    numerical:
      order: asc
