apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- llama-cpp-cpu.yaml
- imagerepository.yaml
- imagepolicy.yaml
images:
- name: ghcr.io/ggml-org/llama.cpp
  newTag: server # {"$imagepolicy": "flux-system:llama-cpp-cpu:tag"}
