apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- imagerepository.yaml
- imagepolicy.yaml
configMapGenerator:
- name: assist-llm-router-config
  namespace: homeassistant-assist
  files:
  - config.yaml=config.yaml
