apiVersion: v1
kind: Service
metadata:
  name: assist-llm-router
  namespace: homeassistant-assist
  labels:
    app.kubernetes.io/name: assist-llm-router
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: assist-llm-router
