unbound:
  port: ${dns_svc_port:=53}
  zones:
    volumeName: unbound-zones
    include_default: false
    existingConfigMap: unbound-zones
  unboundConf:
    volumeName: unbound-conf
  config:
    volumeName: unbound-config
    existingConfigMap: unbound-config
redis:
  enabled: true
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
  resources:
    requests:
      memory: 24Mi
    limits:
      memory: 64Mi
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  sysctls:
  - name: net.ipv4.ip_unprivileged_port_start
    value: "0"
env:
  DISABLE_SET_PERMS: "true"
image:
  tag: "1.26.1-1" # {"$imagepolicy": "flux-system:unbound:tag"}
service:
  main:
    type: ClusterIP
    clusterIP: ${unbound_cluster_ip}
resources:
  requests:
    memory: 450Mi
