apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- disallow-latest-tag.yaml
- disallow-privileged-containers.yaml
- disallow-host-namespaces.yaml
- require-run-as-nonroot.yaml
- require-requests-limits.yaml
- require-labels.yaml
- restrict-image-registries.yaml
