apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-monitoring
  namespace: flux-system
spec:
  interval: 5m0s
  prune: false
  dependsOn:
  - name: infrastructure-platform
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring/livingroom-pi
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: vmagent-livingroom-pi
    namespace: monitoring
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-infrastructure-vars
      optional: false
    - kind: Secret
      name: cluster-vars
      optional: true
