tolerations:
- key: "CriticalAddonsOnly"
  operator: "Exists"
  effect: "NoSchedule"
configuration:
  kubernetes:
    skipTlsVerify: true
  logging:
    minimumLevel: Information
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
resources:
  requests:
    memory: 256Mi
  limits:
    memory: 512Mi
