tolerations:
- key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
installCRDs: 'true'
webhook:
  resources:
    limits:
      memory: 175Mi
      cpu: 500m
    requests:
      memory: 64Mi
      cpu: "0"
resources:
  requests:
    memory: 128Mi
    cpu: "0"
  limits:
    memory: 175Mi
    cpu: 400m
cainjector:
  resources:
    limits:
      memory: 320Mi
      cpu: 800m
    requests:
      cpu: "0"
      memory: 192Mi
