apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: patroni-17
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: patroni-17
  filterTags:
    pattern: '^\d+\.\d+\.\d+-\d+$'
  policy:
    semver:
      range: "~4.0.0-0"
