image:
  tag: "9.20"

hostname: bind9

progressDeadlineSeconds: 600

args:
- -g
- '-4'
- -n 2
- -c
- /etc/bind/named.conf

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 300Mi

bind9:
  namedConfGenerator:
    enabled: true
  zoneCopy:
    enabled: true
    overwrite: false
podSecurityContext:
  runAsNonRoot: true
  sysctls:
  - name: net.ipv4.ip_unprivileged_port_start
    value: '0'
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
persistence:
  bind-etc:
    enabled: true
    mount:
    - path: /etc/bind
    spec:
      emptyDir: {}
