apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich--immich
  namespace: flux-system
spec:
  dependsOn:
  - name: immich--immich-patroni
    namespace: flux-system
  releaseName: immich
  interval: 5m
  targetNamespace: immich
  valuesFrom:
  - kind: ConfigMap
    name: immich-values
    valuesKey: values-base.yaml
  - kind: ConfigMap
    name: immich-values
    valuesKey: values-shared.yaml
  - kind: ConfigMap
    name: immich-values
    optional: true
    valuesKey: values.yaml
  - kind: ConfigMap
    name: immich-helmrelease-overrides
    optional: true
    valuesKey: values.yaml
