apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/policy-reporter
- services.yaml
patches:
- target:
    kind: HelmRelease
    name: policy-reporter--policy-reporter
  patch: |
    - op: add
      path: /spec/values
      value:
        ui:
          name: tpi-1
