apiVersion: v1
kind: Service
metadata:
  name: policy-reporter-ui-tpi-1
  namespace: policy-reporter
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "local"
spec:
  selector:
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/name: policy-reporter-ui
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: policy-reporter-ui-nas
  namespace: policy-reporter
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "remote"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
