config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    extensionApis:
      enableBackend: true
    logging:
      level:
        default: info
deployment:
  envoyGateway:
    resources:
      requests:
        cpu: "0"
certgen:
  job:
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 64Mi
