apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    kind: ^(ConfigMap|Deployment|EnvoyExtensionPolicy|HelmRelease|HelmRepository|HTTPRoute|PersistentVolume|PersistentVolumeClaim|SecurityPolicy|Service|TCPRoute)$
  patch: |
    apiVersion: v1
    kind: Unused
    metadata:
      name: unused
      labels:
        homelab.wahoo.li/ai-workload: "true"
