apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/assist-llm-cpu
- pvc.yaml
- httproute-private.yaml
- securitypolicy.yaml
patches:
- path: inferenceservice.yaml
  target:
    kind: InferenceService
  options:
    allowNameChange: true
