apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: assist-llm-apikey
  namespace: homeassistant-assist
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: assist-llm-cpu-private
  apiKeyAuth:
    extractFrom:
    - headers:
      - Authorization
    credentialRefs:
    - group: ""
      kind: Secret
      name: assist-llm-api-keys
