apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/envoy-gateway
patches:
- path: envoy-proxy-patch.yaml
  target:
    kind: EnvoyProxy
    name: envoy-proxy-config
