redis:
  enabled: true
redisSidecar:
  enabled: false

image:
  repository: madnuttah/unbound

hostname: unbound

progressDeadlineSeconds: 600

resources:
  limits:
    memory: 640Mi
  requests:
    memory: 450Mi
