apiVersion: v1
kind: PersistentVolume
metadata:
  name: wyoming-whisper-models
  labels:
    app.kubernetes.io/name: wyoming-whisper
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: voice-assist
    name: wyoming-whisper-models
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: wyoming-whisper-models
    volumeAttributes:
      path: /buckets/wyoming-whisper-models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-models
  namespace: voice-assist
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: wyoming-whisper-models
  resources:
    requests:
      storage: 5Gi
