apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: wyoming-whisper
  namespace: voice-assist
spec:
  parentRefs:
  - name: envoy-gw-voice
    namespace: envoy-gateway-system
    sectionName: wyoming-whisper
  rules:
  - backendRefs:
    - name: wyoming-whisper
      port: 10300
