apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/assist-llm-router
- httproute-private.yaml
- securitypolicy.yaml
images:
- name: ghcr.io/berriai/litellm
  newTag: v1.83.7-stable.patch.1 # {"$imagepolicy": "flux-system:assist-llm-router:tag"}
