apiVersion: v1
kind: ConfigMap
metadata:
  name: topolvm-local-overrides
  namespace: flux-system
data:
  values.yaml: |
    lvmd:
      managed: false
    node:
      nodeSelector:
        topolvm.io/enabled: "true"
    storageClasses: []
