apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: base-assist-llm-gpu
  namespace: homeassistant-assist
  labels:
    networking.knative.dev/visibility: cluster-local
  annotations:
    autoscaling.knative.dev/scale-down-delay: "10m"
    autoscaling.knative.dev/window: "60s"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    scaleTarget: 1
    scaleMetric: concurrency
    timeout: 9000
    runtimeClassName: nvidia
    model:
      modelFormat:
        name: vllm
      runtime: vllm-cuda
      args:
      - --model
      - cosmicproc/Qwen3.5-4B-NVFP4
      - --served-model-name
      - assist-llm
      - --max-model-len
      - "102400"
      - --gpu-memory-utilization
      - "0.4"
      - --kv-cache-memory-bytes
      - "4294967296"
      - --max-num-seqs
      - "16"
      - --enable-auto-tool-choice
      - --tool-call-parser
      - qwen3_xml
      - --default-chat-template-kwargs
      - '{"enable_thinking":false}'
      resources:
        requests:
          cpu: 500m
          memory: 4Gi
        limits:
          cpu: "4"
          memory: 8Gi
