apiVersion: v1
kind: Service
metadata:
  name: immich-syncthing-tpi-1
  namespace: immich
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "remote"
spec:
  type: ClusterIP
  ports:
  - name: sync
    port: 22000
    targetPort: 22000
