apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 10Ti
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: ${immich_library_host_path}
    type: DirectoryOrCreate
  claimRef:
    name: immich-library
    namespace: immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 10Ti
