apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
configMapGenerator:
- name: hermes-agent-config
  namespace: hermes-agent
  files:
  - config.yaml=config.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
