apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cloudflare-external-dns
  namespace: monitoring
spec:
  endpoints:
  - port: http
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - cloudflare-dns
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
