apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-gw-public-policy
  namespace: envoy-gateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gw
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  headers:
    enableEnvoyHeaders: false
  connection:
    connectionLimit:
      value: 10000
  proxyProtocol: {}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-gw-private-policy
  namespace: envoy-gateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gw-private
  http3: {}
  headers:
    enableEnvoyHeaders: false
