apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: envoy-gateway-system
spec:
  telemetry:
    accessLog:
      settings:
      - format:
          type: JSON
          json:
            timestamp: "%START_TIME%"
            method: "%REQ(:METHOD)%"
            path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            protocol: "%PROTOCOL%"
            status: "%RESPONSE_CODE%"
            response_code_details: "%RESPONSE_CODE_DETAILS%"
            response_flags: "%RESPONSE_FLAGS%"
            bytes_received: "%BYTES_RECEIVED%"
            bytes_sent: "%BYTES_SENT%"
            duration: "%DURATION%"
            request_duration: "%REQUEST_DURATION%"
            response_duration: "%RESPONSE_DURATION%"
            upstream_host: "%UPSTREAM_HOST%"
            upstream_cluster: "%UPSTREAM_CLUSTER%"
            upstream_request_attempt_count: "%UPSTREAM_REQUEST_ATTEMPT_COUNT%"
            downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
            x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
            user_agent: "%REQ(USER-AGENT)%"
            request_id: "%REQ(X-REQUEST-ID)%"
            authority: "%REQ(:AUTHORITY)%"
            route_name: "%ROUTE_NAME%"
            requested_server_name: "%REQUESTED_SERVER_NAME%"
        sinks:
        - type: File
          file:
            path: /dev/stdout
    metrics:
      prometheus:
        disable: false
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
        pod:
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: proxy
                app.kubernetes.io/managed-by: envoy-gateway
