apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: media-streaming
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: plex
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: jellyfin
  timeout:
    http:
      connectionIdleTimeout: 3600s
      requestTimeout: 0s
