apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "remote"
    service.cilium.io/global-sync-endpoint-slices: "true"
  name: blocky-tpi-1
  namespace: internal-dns
spec:
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 4000
  type: ClusterIP
