service:
  nas:
    annotations:
      service.cilium.io/global: "true"
      service.cilium.io/affinity: "local"
      service.cilium.io/global-sync-endpoint-slices: "true"
    type: ClusterIP
    portsFrom: main
