apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: velero
  namespace: velero
spec:
  endpoints:
  - port: http-monitoring
  namespaceSelector:
    matchNames:
    - velero
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
