apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-ldap-auth
  namespace: default
  labels:
    velero.io/exclude-from-backup: "true"
stringData:
  # copied over /config/plugins/configurations/LDAP-Auth.xml by the ldap-auth-config init container on every pod start
  LDAP-Auth.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <LdapUsers />
      <LdapServer>ak-outpost-authentik-ldap-outpost.authentik.svc.cluster.local.</LdapServer>
      <LdapPort>389</LdapPort>
      <UseSsl>false</UseSsl>
      <UseStartTls>false</UseStartTls>
      <SkipSslVerify>false</SkipSslVerify>
      <LdapBindUser>cn=jellyfin-ldap-bind-user,ou=users,dc=ldap,dc=goauthentik,dc=io</LdapBindUser>
      <LdapBindPassword><![CDATA[${authentik_jellyfin_bind_user_password}]]></LdapBindPassword>
      <LdapBaseDn>dc=ldap,dc=goauthentik,dc=io</LdapBaseDn>
      <LdapSearchFilter>(&amp;(memberOf=cn=Jellyfin Users,ou=groups,dc=ldap,dc=goauthentik,dc=io)(ak-active=TRUE)(!(disable-normal-login=true)))</LdapSearchFilter>
      <LdapAdminBaseDn />
      <LdapAdminFilter>(memberOf=cn=Jellyfin Admins,ou=groups,dc=ldap,dc=goauthentik,dc=io)</LdapAdminFilter>
      <EnableLdapAdminFilterMemberUid>false</EnableLdapAdminFilterMemberUid>
      <LdapSearchAttributes>uid, cn, mail, displayName</LdapSearchAttributes>
      <LdapClientCertPath />
      <LdapClientKeyPath />
      <LdapRootCaPath />
      <CreateUsersFromLdap>true</CreateUsersFromLdap>
      <AllowPassChange>false</AllowPassChange>
      <LdapUidAttribute>uid</LdapUidAttribute>
      <LdapUsernameAttribute>cn</LdapUsernameAttribute>
      <LdapPasswordAttribute>userPassword</LdapPasswordAttribute>
      <EnableLdapProfileImageSync>false</EnableLdapProfileImageSync>
      <RemoveImagesNotInLdap>false</RemoveImagesNotInLdap>
      <LdapProfileImageAttribute>jpegphoto</LdapProfileImageAttribute>
      <LdapProfileImageFormat>Default</LdapProfileImageFormat>
      <EnableAllFolders>true</EnableAllFolders>
      <EnabledFolders>
        <string>f137a2dd21bbc1b99aa5c0f6bf02a805</string>
        <string>5ddaa59a73205234890fdcfc683e14ed</string>
      </EnabledFolders>
      <PasswordResetUrl />
    </PluginConfiguration>
