apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kokoro-tts-models
  namespace: homeassistant-assist
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: topolvm-fast
  resources:
    requests:
      storage: 2Gi
