apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: forgejo-private-ip-allow
  namespace: forgejo
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: forgejo-private
  authorization:
    defaultAction: Deny
    rules:
    - name: allow-private
      action: Allow
      principal:
        clientCIDRs:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
