controller:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: nginx.nas.${domain_absolutist_it:=absolutist.it},nginx.nas.${domain_wahoo_li:=wahoo.li}
      # lbipam.cilium.io/ips: ${nginx_lb_ip}
