apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ca-certificate.yaml
- cluster-issuer-production.yaml
- cluster-issuer-selfsigned-ca.yaml
- cluster-issuer-selfsigned.yaml
- cluster-issuer-staging.yaml
- clustermesh-issuer.yaml
