apiVersion: v1
kind: Service
metadata:
  name: wyoming-openai
  namespace: homeassistant-assist
  labels:
    app.kubernetes.io/name: wyoming-openai
spec:
  type: ClusterIP
  ports:
  - name: wyoming-tts
    port: 10200
    targetPort: wyoming-tts
    protocol: TCP
  - name: wyoming-stt
    port: 10300
    targetPort: wyoming-stt
    protocol: TCP
  selector:
    app.kubernetes.io/name: wyoming-openai
