apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/envoy-gateway
- gateway-ai-alias.yaml
- gateway-ai-stub-nas.yaml
patches:
- path: envoy-proxy-patch.yaml
  target:
    kind: EnvoyProxy
    name: envoy-proxy-config
