apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: wyoming-whisper-gpu
  namespace: homeassistant-assist
  labels:
    app.kubernetes.io/name: wyoming-whisper-gpu
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/autoscalerClass: "none"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    runtimeClassName: nvidia
    containers:
    - name: wyoming-whisper-gpu
      image: lscr.io/linuxserver/faster-whisper:gpu
      imagePullPolicy: IfNotPresent
      env:
      - name: WHISPER_MODEL
        value: medium
      - name: WHISPER_LANG
        value: en
      - name: WHISPER_BEAM
        value: "1"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: UTC
      ports:
      - containerPort: 10300
        name: wyoming
        protocol: TCP
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 4Gi
      readinessProbe:
        tcpSocket:
          port: wyoming
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 60
      livenessProbe:
        tcpSocket:
          port: wyoming
        initialDelaySeconds: 180
        periodSeconds: 30
        failureThreshold: 3
