apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/redis/helmrelease.yaml
patches:
- path: helmrelease.yaml
  target:
    kind: HelmRelease
    name: base-redis
  options:
    allowNameChange: true
configMapGenerator:
- files:
  - values-shared.yaml=values-shared.yaml
  name: forgejo-redis-values
  namespace: flux-system
  options:
    labels:
      velero.io/exclude-from-backup: "true"
configurations:
- ../../../.config/valuesFrom.yaml
- ../../../.config/envFrom.yaml
