global:
  labels:
    backupWeekly: "true"
    backupDaily: "true"
  redis:
    redis:
      sentinel:
        masterName: forgejomaster
    cluster:
      ordinals:
        start: 0
      replicaCount: 3

redis:
  initialMaster: 0
  enabled: true
  sentinel:
    enabled: true

certificates:
  server:
    secretTemplate:
      labels:
        velero.io/exclude-from-backup: "true"

ssl:
  enabled: false
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer

podAnnotations:
  secret.reloader.stakater.com/reload: "redis-server"

dnsConfig:
  options:
  - name: ndots
    value: "1"
  - name: edns0

service:
  main:
    annotations:
      service.cilium.io/global: "true"
      service.cilium.io/global-sync-endpoint-slices: "true"
  sentinel:
    annotations:
      service.cilium.io/global: "true"

haproxy:
  podAnnotations:
    secret.reloader.stakater.com/reload: "redis-server"
  enabled: false
  image:
    repository: haproxy-redis

persistence:
  data:
    enabled: true
    mount:
    - path: /data
    labels:
      velero.io/exclude-from-backup: "true"
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
