apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik
  namespace: default
  labels:
    app.kubernetes.io/name: authentik-remote-cluster
    app.kubernetes.io/part-of: authentik
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: default
  labels:
    app.kubernetes.io/name: authentik-remote-cluster
    app.kubernetes.io/part-of: authentik
  annotations:
    kubernetes.io/service-account.name: authentik
type: kubernetes.io/service-account-token
