apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../shared/authentik
- patroni
- redis
configMapGenerator:
- name: authentik-values
  namespace: flux-system
  behavior: merge
  files:
  - values.yaml=values.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
patches:
- target:
    kind: Deployment
    name: authentik-apply-blueprints
  patch: |
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: authentik-apply-blueprints
