apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/cert-manager
patches:
- target:
    kind: HelmRelease
    name: cert-manager--cert-manager
  patch: |
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: cert-manager--cert-manager
    spec:
      dependsOn:
      - name: envoy-gateway-system--envoy-gateway
configMapGenerator:
- name: cert-manager-values
  namespace: flux-system
  behavior: merge
  files:
  - values-extra.yaml=values-extra.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
configurations:
- ../../../.config/valuesFrom.yaml
