apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/open-webui
- httproute-private.yaml
patches:
- path: helmrelease.yaml
  target:
    kind: HelmRelease
  options:
    allowNameChange: true
