serviceMonitor:
  enabled: false
logLevel: error
image:
  pullPolicy: IfNotPresent
  repository: registry.k8s.io/external-dns/external-dns
tolerations:
- key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
