serviceMonitor:
  enabled: false
logLevel: error
image:
  pullPolicy: IfNotPresent
  repository: registry.k8s.io/external-dns/external-dns
tolerations:
- key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
resources:
  requests:
    cpu: 10m
    memory: 96Mi
  limits:
    memory: 160Mi
