{
 "title": "Blocky queries",
 "tags": [
  "DNS",
  "Blocky",
  "Logs"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "client_ip",
    "label": "Client IP",
    "query": {
     "query": "{source_type=\"kubernetes_logs\", kubernetes.pod_labels.app_kubernetes_io_name=\"blocky\"}"
    }
   },
   {
    "name": "client_name",
    "label": "Client name",
    "query": {
     "query": "{source_type=\"kubernetes_logs\", kubernetes.pod_labels.app_kubernetes_io_name=\"blocky\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query count by response type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_names: $client_name AND client_ip: $client_ip {source_type=\"kubernetes_logs\", kubernetes.pod_labels.app_kubernetes_io_name=\"blocky\"} | stats by (response_type) count()",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Query count by client",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{source_type=\"kubernetes_logs\", kubernetes.pod_labels.app_kubernetes_io_name=\"blocky\"} | stats by (client_names) count() as queries | order by (queries, client_names) desc ",
     "legendFormat": "{{client_names}}"
    }
   ]
  },
  {
   "title": "Top 20 queried domains",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_names: $client_name AND client_ip: $client_ip {source_type=\"kubernetes_logs\", kubernetes.pod_labels.app_kubernetes_io_name=\"blocky\"} | stats by (question_name) count() as queries | order by (queries, question_name) desc | limit 20",
     "legendFormat": "{{question_name}}"
    }
   ]
  },
  {
   "title": "Query log",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "client_names: $client_name AND client_ip: $client_ip {source_type=\"kubernetes_logs\", kubernetes.pod_labels.app_kubernetes_io_name=\"blocky\"}",
     "maxLines": 10000
    }
   ]
  }
 ]
}