{
 "title": "Media Dashboard",
 "tags": [
  "sonarr",
  "readarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "sabnzbd",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "prowlarr_instance",
    "label": "Prowlarr Instance",
    "query": {
     "query": "label_values({__name__=~\"prowlarr_.*\"},instance)"
    }
   },
   {
    "name": "radarr_instance",
    "label": "Radarr Instance",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"},instance)"
    }
   },
   {
    "name": "sonarr_instance",
    "label": "Sonarr Instance",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"},instance)"
    }
   },
   {
    "name": "lidarr_instance",
    "label": "Lidarr Instance",
    "query": {
     "query": "label_values({__name__=~\"lidarr_.*\"},instance)"
    }
   },
   {
    "name": "readarr_instance",
    "label": "Readarr Instance",
    "query": {
     "query": "label_values({__name__=~\"readarr_.*\"},instance)"
    }
   },
   {
    "name": "bazarr_instance",
    "label": "Bazarr Instance",
    "query": {
     "query": "label_values({__name__=~\"bazarr_.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prowlarr - ${prowlarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "prowlarr_instance"
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_system_status{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"prowlarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total{instance=~\"${prowlarr_instance}\"} - prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) / sum(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(prowlarr_indexer_vip_expires_in_seconds)",
     "legendFormat": "Nearest VIP Expiration"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"}) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__rate_interval])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP Expiration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "prowlarr_indexer_vip_expires_in_seconds{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() * 1000) + (prowlarr_indexer_vip_expires_in_seconds{instance=~\"${prowlarr_instance}\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bazarr - ${bazarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "bazarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_system_status{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"bazarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(bazarr_subtitles_language_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 31 },
   "targets": [
    {
     "expr": "bazarr_system_health_issues{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"bazarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"bazarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bazarr_episode_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Episodes"
    },
    {
     "expr": "bazarr_movie_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Movies"
    },
    {
     "expr": "bazarr_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Subtitle Totals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_queue_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "bazarr_history_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "bazarr_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "bazarr_subtitles_monitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "bazarr_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Unmonitored"
    },
    {
     "expr": "bazarr_subtitles_missing_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "bazarr_subtitles_wanted_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "title": "Episode Subtitles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(bazarr_episode_subtitles_monitored_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Monitored"
    },
    {
     "expr": "max(bazarr_episode_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max(bazarr_episode_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Unmonitored"
    },
    {
     "expr": "max(bazarr_episode_subtitles_wanted_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "title": "Movie Subtitles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(bazarr_movie_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max(bazarr_movie_subtitles_monitored_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Monitored"
    },
    {
     "expr": "max(bazarr_movie_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Unmonitored"
    },
    {
     "expr": "max(bazarr_movie_subtitles_wanted_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Wanted"
    },
    {
     "expr": "max(bazarr_movie_subtitles_missing_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "Missing"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_by_label_numeric_desc(bazarr_subtitles_score_total{instance=~\"${bazarr_instance}\"}, \"score\")",
     "legendFormat": "{{score}}"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(bazarr_subtitles_provider_total{instance=~\"${bazarr_instance}\"})",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  { "title": "Sonarr - ${sonarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }, "repeat": "sonarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_system_status{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"sonarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "sonarr_history_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "sonarr_episode_downloaded_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_series_monitored_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Series Monitored"
    },
    {
     "expr": "max(sonarr_series_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Series Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_season_monitored_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Seasons Monitored"
    },
    {
     "expr": "max(sonarr_season_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Seasons Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_episode_missing_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Episodes Missing"
    },
    {
     "expr": "max(sonarr_episode_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "Episodes Total"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sonarr_episode_quality_total{instance=~\"${sonarr_instance}\"})",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sonarr_series_filesize_bytes{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "targets": [
    {
     "expr": "sonarr_system_health_issues{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Radarr - ${radarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 }, "repeat": "radarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_system_status{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"radarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_movie_monitored_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "radarr_movie_wanted_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_queue_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_history_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "radarr_rootfolder_freespace_bytes{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(radarr_movie_quality_total{instance=~\"${radarr_instance}\"})",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"radarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"radarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 103 },
   "targets": [
    {
     "expr": "radarr_system_health_issues{instance=~\"${radarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Readarr - ${readarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "repeat": "readarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 349 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "readarr_system_status{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{container=\"readarr\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "readarr_author_downloaded_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Authors Downloaded"
      },
      {
       "expr": "readarr_author_monitored_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Authors Monitored"
      },
      {
       "expr": "readarr_author_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Authors Wanted"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "readarr_queue_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "readarr_book_downloaded_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Downloaded"
      },
      {
       "expr": "readarr_history_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "History"
      },
      {
       "expr": "readarr_author_filesize_bytes{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Disk Used"
      },
      {
       "expr": "readarr_rootfolder_freespace_bytes{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Disk Free"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"readarr.*\"}[$__rate_interval]))",
       "legendFormat": "Network Transmit"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"readarr.*\"}[$__rate_interval])) * -1",
       "legendFormat": "Network Receive"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "readarr_author_filesize_bytes{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 376 },
     "targets": [
      {
       "expr": "readarr_system_health_issues{instance=~\"${readarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Lidarr - ${lidarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "repeat": "lidarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 350 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lidarr_system_status{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 350 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{container=\"lidarr\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "title": "Songs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 6, "y": 350 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lidarr_queue_total{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "lidarr_songs_downloaded_total{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Downloaded"
      },
      {
       "expr": "lidarr_songs_total - lidarr_songs_downloaded_total",
       "legendFormat": "Missing"
      },
      { "expr": "lidarr_songs_total", "legendFormat": "Total" }
     ]
    },
    {
     "title": "Artists",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 14, "y": 350 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(lidarr_artists_monitored_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Monitored"
      },
      {
       "expr": "max(lidarr_artists_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Albums",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 350 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(lidarr_albums_monitored_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Monitored"
      },
      {
       "expr": "max(lidarr_albums_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "max(lidarr_albums_missing_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Missing"
      }
     ]
    },
    {
     "title": "Song Qualities",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 354 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lidarr_songs_quality_total{instance=~\"${lidarr_instance}\"}\r\n",
       "legendFormat": "{{quality}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 364 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"lidarr.*\"}[$__rate_interval]))",
       "legendFormat": "Network Transmit"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"lidarr.*\"}[$__rate_interval])) * -1",
       "legendFormat": "Network Receive"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 364 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lidarr_artists_filesize_bytes{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 364 },
     "targets": [
      {
       "expr": "lidarr_system_health_issues{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}