{
 "title": "Systemd logs",
 "tags": [
  "Logs",
  "Systemd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "host", "query": { "query": "source_type: journald" } },
   {
    "name": "unit",
    "label": "Systemd unit",
    "query": {
     "query": "source_type:=\"journald\" | systemd_host:=$host"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lines per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "systemd_host: $host AND systemd_unit: $unit {source_type=\"journald\", systemd_unit!=\"\"} | stats count() Lines"
    }
   ]
  },
  {
   "title": "Rows by unit",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "systemd_host:=$host {source_type=\"journald\", systemd_unit!=\"\"} | stats(systemd_unit) count() as entries | order by(entries) desc | pack_json",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "systemd_unit: $unit AND systemd_host: $host {source_type=\"journald\"}"
    }
   ]
  }
 ]
}