{
 "title": "Vector K8S Monitoring",
 "description": "Vector.dev Kubernetes cluster monitoring dashboard",
 "tags": [ "vm-k8s-stack" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": ".*" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(vector_build_info,instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vector_component_received_events_total{component_type=\"kubernetes_logs\"},pod_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log events by top 10 namespaces (events/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10, sum by (component_id, cluster, pod_namespace) (rate(vector_component_received_events_total{component_kind=\"source\", pod_namespace=~\"$namespace\", cluster=~\"$cluster\", instance=~\"$instance\"}[1m])))",
       "legendFormat": "{{ component_id }}: {{ pod_namespace }}"
      }
     ]
    },
    {
     "title": "Log bytes by top 10 namespaces (bytes/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(10, sum by (component_id, pod_namespace) (rate(vector_component_received_event_bytes_total{component_kind=\"source\", pod_namespace=~\"$namespace\", cluster=~\"$cluster\", instance=~\"$instance\"}[1m])))",
       "legendFormat": "{{ component_id }}: {{ pod_namespace }}"
      }
     ]
    },
    {
     "title": "Log events by top 10 pods (events/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10, sum by (component_id, pod_name) (rate(vector_component_received_events_total{component_kind=\"source\", pod_namespace=~\"$namespace\", cluster=~\"$cluster\", instance=~\"$instance\"}[1m])))",
       "legendFormat": "{{ component_id }}: {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Log bytes by top 10 pods (bytes/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(10, sum by (pod_name, component_id) (rate(vector_component_received_event_bytes_total{component_kind=\"source\", pod_namespace=~\"$namespace\", cluster=~\"$cluster\", instance=~\"$instance\"}[1m])))",
       "legendFormat": "{{ component_id }}: {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Events lag seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(vector_source_lag_time_seconds_bucket{ cluster=~\"$cluster\", instance=~\"$instance\"}[5m])) by (le,component_type, instance))",
       "legendFormat": "{{component_type}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (component_id, instance) (vector_open_files{component_kind=\"source\", cluster=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{component_id}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (component_id, error_type) (vector_component_errors_total{component_kind=\"source\", cluster=~\"$cluster\", instance=~\"$instance\"}) or 0",
       "legendFormat": "{{component_id}}: {{error_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transform",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events bytes rate (bytes/sec)",
     "type": "timeseries",
     "description": "The rate of bytes processed by the component.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (component_id, instance) (rate(vector_component_received_event_bytes_total{component_kind=\"transform\", cluster=~\"$cluster\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{ component_id }}: {{ instance }}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (component_id, instance) (vector_utilization{component_kind=\"transform\", cluster=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{component_id}}: {{ instance }}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (component_id, error_type) (vector_component_errors_total{component_kind=\"transform\", cluster=~\"$cluster\", instance=~\"$instance\"}) or 0",
       "legendFormat": "{{component_id}}: {{error_type}}"
      }
     ]
    },
    {
     "title": "Discarded events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (component_id, reason) (vector_events_discarded_total{component_kind=\"transform\", cluster=~\"$cluster\", instance=~\"$instance\"}) or 0",
       "legendFormat": "{{component_id}}: {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events rate (events/sec)",
     "type": "timeseries",
     "description": "The count of bytes processed by the component.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (component_id, instance) (rate(vector_component_received_events_total{component_kind=\"sink\", cluster=~\"$cluster\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{ component_id }}: {{ instance }}"
      }
     ]
    },
    {
     "title": "Events bytes rate (bytes/sec)",
     "type": "timeseries",
     "description": "The rate of bytes processed by the component.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (component_id, instance) (rate(vector_component_received_event_bytes_total{component_kind=\"sink\", cluster=~\"$cluster\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{ component_id }}: {{ instance }}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (component_id, instance) (vector_utilization{component_kind=\"sink\", cluster=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{component_id}}: {{ instance}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (component_id, error_type) (vector_component_errors_total{component_kind=\"sink\", cluster=~\"$cluster\", instance=~\"$instance\"}) or 0",
       "legendFormat": "{{component_id}}: {{error_type}}"
      }
     ]
    }
   ]
  }
 ]
}