apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: forgejo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: forgejo
  filterTags:
    pattern: '^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)-rootless$'
    extract: '$major.$minor.$patch'
  policy:
    semver:
      range: '>=14.0.0'
