{
 "title": "Cloudflare tunnel",
 "tags": [
  "cloudflared",
  "ingress"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cloudflared_orchestration_config_version,job)"
    }
   },
   {
    "name": "ha_connections",
    "query": {
     "query": "query_result(topk(1, cloudflared_tunnel_ha_connections{job=\"$job\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cloudflared version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (build_info{job=\"$job\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests in time range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflared_tunnel_total_requests{job=\"$job\"}[$__range]))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(rate(sum(cloudflared_tunnel_total_requests{job=\"$job\"})[$__rate_interval]), 0.1)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connected edge locations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (edge_location) (cloudflared_tunnel_server_locations{job=\"$job\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min RTT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (node_name) (quic_client_min_rtt{job=\"$job\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Smoothed RTT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (node_name) (quic_client_smoothed_rtt{job=\"$job\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Max RTT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (node_name) (max_over_time(quic_client_latest_rtt{job=\"$job\"}[$__range]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HA connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "workers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, cloudflared_tunnel_ha_connections{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(cloudflared_tunnel_total_requests{job=\"$job\"}[1m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Request round trip time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(node_name) (quic_client_latest_rtt{job=\"$job\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Connection graph",
   "type": "nodeGraph",
   "gridPos": { "h": 21, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "label_join(\n  label_replace(\n    label_replace(\n      label_replace(\n        sum without (connection_id) (cloudflared_tunnel_server_locations{job=\"$job\"})\n      , \"source\", \"$1\", \"node_name\", \"(.+)\")\n    , \"target\", \"$1\", \"edge_location\", \"(.+)\")\n  , \"color\", \"#73bf69\", \"new_label\", \".*\")\n, \"id\", \"--\", \"source\", \"target\")",
     "legendFormat": "edges"
    },
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          sum without (instance, connection_id, pod) (increase(cloudflared_tunnel_server_locations{job=\"$job\"}[$__range]))\n        , \"id\", \"$1\", \"edge_location\", \"(.+)\")\n      , \"subtitle\", \"cloudflare\", \"new_label\", \".*\") \n    , \"icon\", \"cloud\", \"new_label\", \".*\") \n  , \"color\", \"#f6821f\", \"new_label\", \".*\") \n  or \n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          sum without (instance, connection_id, edge_location) (increase(cloudflared_tunnel_server_locations{job=\"$job\"}[$__range]))\n        , \"id\", \"$1\", \"node_name\", \"(.+)\")\n      , \"subtitle\", \"$1\", \"clustername\", \"(.+)\")\n    , \"icon\", \"kubernetes\", \"new_label\", \".*\") \n  , \"color\", \"#326ce5\", \"new_label\", \".*\") \n, \"title\", \"$1\", \"id\", \"(.+)\")\n",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Response by code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(cloudflared_tunnel_response_by_code{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Client lost packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum by(reason) (increase(quic_client_lost_packets{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Config updates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "avg(changes(cloudflared_orchestration_config_version{job=\"$job\"}[$__interval]))",
     "legendFormat": "Config updates"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(cloudflared_tunnel_request_errors{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Request errors"
    }
   ]
  }
 ]
}