{
 "title": "Pod logs",
 "tags": [
  "Logs",
  "Kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "clustername:~\"$clustername\" {source_type=\"kubernetes_logs\"} "
    }
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": {
     "query": "{source_type=\"kubernetes_logs\"} "
    }
   },
   {
    "name": "pod",
    "label": "Pod name",
    "query": {
     "query": "clustername:~\"$clustername\" kubernetes.pod_labels.app_kubernetes_io_name:~$name kubernetes.pod_labels.app_kubernetes_io_instance:~$instance {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"} "
    }
   },
   {
    "name": "container_name",
    "label": "Container name",
    "query": {
     "query": "clustername:~\"$clustername\" kubernetes.pod_name: $pod kubernetes.pod_labels.app_kubernetes_io_name:~$name kubernetes.pod_labels.app_kubernetes_io_instance:~$instance {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"} "
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "clustername:~\"$clustername\" {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"} "
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "clustername:~\"$clustername\" {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"} "
    }
   },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Lines per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$filter clustername:~\"$clustername\" kubernetes.pod_name: $pod kubernetes.container_name: $container_name kubernetes.pod_labels.app_kubernetes_io_name:~$name kubernetes.pod_labels.app_kubernetes_io_instance:~$instance {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"} | stats rate() as lines_per_second"
    }
   ]
  },
  {
   "title": "Lines per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "$filter clustername:~\"$clustername\" kubernetes.pod_name: $pod kubernetes.container_name: $container_name kubernetes.pod_labels.app_kubernetes_io_name:~$name kubernetes.pod_labels.app_kubernetes_io_instance:~$instance {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"} | stats count() Lines"
    }
   ]
  },
  {
   "title": "Rows by pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "$filter clustername:~\"$clustername\" kubernetes.pod_name: $pod kubernetes.container_name: $container_name kubernetes.pod_labels.app_kubernetes_io_name:~$name kubernetes.pod_labels.app_kubernetes_io_instance:~$instance {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"} | stats(kubernetes.pod_name) count() as entries | order by(entries) desc | pack_json"
    }
   ]
  },
  {
   "title": "Lines in timerange",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$filter clustername:~\"$clustername\" kubernetes.pod_name: $pod kubernetes.container_name: $container_name kubernetes.pod_labels.app_kubernetes_io_name:~$name kubernetes.pod_labels.app_kubernetes_io_instance:~$instance {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"}| stats count() as lines"
    }
   ]
  },
  {
   "title": "Pod logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "$filter clustername:~\"$clustername\" kubernetes.container_name: $container_name kubernetes.pod_name: $pod kubernetes.pod_labels.app_kubernetes_io_name:~$name kubernetes.pod_labels.app_kubernetes_io_instance:~$instance {source_type=\"kubernetes_logs\", kubernetes.pod_namespace=\"$namespace\"}",
     "maxLines": 50000
    }
   ]
  }
 ]
}