apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/seaweedfs-csi-driver
patches:
- target:
    kind: HelmRelease
    name: seaweedfs--seaweedfs-csi-driver
  patch: |
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: seaweedfs--seaweedfs-csi-driver
    spec:
      values:
        mount:
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 256Mi
