apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/seaweedfs-csi-driver
configMapGenerator:
- name: seaweedfs-csi-driver-values
  namespace: flux-system
  behavior: merge
  files:
  - values.yaml=values.yaml
