apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo--forgejo-patroni
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager--cert-manager
    namespace: flux-system
  - name: reflector--reflector
    namespace: flux-system
  - name: etcd--etcd
    namespace: flux-system
  releaseName: forgejo-patroni
  interval: 5m
  targetNamespace: forgejo
  valuesFrom:
  - kind: ConfigMap
    name: forgejo-patroni-values
    valuesKey: values-shared.yaml
  - kind: ConfigMap
    name: forgejo-patroni-values
    optional: true
    valuesKey: values.yaml
  - kind: ConfigMap
    name: forgejo-patroni-helmrelease-overrides
    optional: true
    valuesKey: values.yaml
