apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: default
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "remote"
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  type: ClusterIP
