apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
    service.cilium.io/affinity: "local"
  name: vector-global-write-mesh
  namespace: logging
spec:
  selector:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector-global-write
    app.kubernetes.io/name: vector
  ports:
  - name: vector
    port: 6000
    protocol: TCP
    targetPort: 6000
  type: ClusterIP
