image:
  tag: "2.3.5" # {"$imagepolicy": "flux-system:prowlarr:tag"}
podAnnotations:
  backup.velero.io/backup-volumes: config
  vector.dev/exclude-containers: "prowlarr-exporter"
strategy:
  type: Recreate
dnsConfig:
  options:
  - name: ndots
    value: "1"
  - name: edns0
global:
  labels:
    backupWeekly: "true"
    backupDaily: "true"
    app.kubernetes.io/part-of: prowlarr
# resources:
#   requests:
#     memory: "256Mi"
#     cpu: "400m"
#   limits:
#     memory: "3072Mi"
#     cpu: "1000m"
metrics:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 60Mi
serviceMonitor:
  create: true
  jobLabel: app.kubernetes.io/name
  endpoint:
    metricRelabelConfigs:
    - action: replace
      replacement: nasse
      target_label: instance
    - action: labeldrop
      regex: (pod|container|image_id|url|endpoint|namespace|prometheus)
persistence:
  config:
    enabled: true
    mount:
    - path: /config
    spec:
      isPersistentVolumeClaim: true
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Gi"
service:
  main:
    annotations:
      service.cilium.io/global: "true"
      service.cilium.io/affinity: "local"
ingress:
  main:
    enabled: false
