apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/wyoming-piper
- pvc.yaml
- tcproute.yaml
images:
- name: rhasspy/wyoming-piper
  newTag: 2.2.2 # {"$imagepolicy": "flux-system:wyoming-piper:tag"}
