apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/zot
configMapGenerator:
- name: zot-values
  namespace: flux-system
  behavior: merge
  files:
  - values-extra.yaml=values-extra.yaml
  options:
    labels:
      velero.io/exclude-from-backup: "true"
- name: zot-config
  namespace: flux-system
  behavior: replace
  files:
  - config.json=config.json
  options:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "registry"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "registry"
configurations:
- ../../../.config/valuesFrom.yaml
- ../../base/zot/configMapRef.yaml
