apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/kserve-crd
patches:
- path: helmrelease.yaml
  target:
    kind: HelmRelease
    name: base-kserve-crd
  options:
    allowNameChange: true
