apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/forgejo-runner
configMapGenerator:
- name: forgejo-runner-registration
  namespace: forgejo-runners
  files:
  - registration.yaml=registration.yaml
  options:
    disableNameSuffixHash: true
patches:
- path: scaledjob-patch.yaml
  target:
    kind: ScaledJob
    name: forgejo-runner
- target:
    kind: ScaledJob
    name: forgejo-runner
  patch: |
    - op: replace
      path: /spec/triggers/0/metadata/labels
      value: "linux,linux-amd64,java,dotnet,go,rust,js"
