image:
  tag: "1.5.6" # {"$imagepolicy": "flux-system:bazarr:tag"}
podAnnotations:
  backup.velero.io/backup-volumes: config
  vector.dev/exclude-containers: "bazarr-exporter"
strategy:
  type: Recreate
dnsConfig:
  options:
  - name: ndots
    value: "1"
  - name: edns0
global:
  labels:
    backupWeekly: "true"
    backupDaily: "true"
    app.kubernetes.io/part-of: bazarr
metrics:
  enabled: true
  # dockerModsUrl: ghcr.io/linuxserver/mods
  extraEnv:
    ENABLE_ADDITIONAL_METRICS: "true"
  resources:
    limits:
      cpu: 150m
      memory: 60Mi
serviceMonitor:
  create: true
  jobLabel: app.kubernetes.io/name
  endpoint:
    interval: 300s # additional metrics makes scraping slow, and here's not that time sensitive data anyway
    scrapeTimeout: 60s
    metricRelabelConfigs:
    - action: replace
      replacement: nasse
      target_label: instance
    - action: labeldrop
      regex: (pod|container|image_id|url|endpoint|namespace|prometheus)
envFrom:
  envs:
    type: configMap
    useFromChart: false
    name: bazarr-env
# resources:
#   requests:
#     memory: "256Mi"
#     cpu: "400m"
#   limits:
#     memory: "3072Mi"
#     cpu: "1000m"
persistence:
  config:
    enabled: true
    mount:
    - path: /config
    spec:
      isPersistentVolumeClaim: true
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Gi"
  movies:
    enabled: true
    mount:
    - path: /movies
    spec:
      hostPath:
        path: ${bazarr_movies_host_path}
        type: Directory
  tv:
    enabled: true
    mount:
    - path: /tv
    spec:
      hostPath:
        path: ${bazarr_tv_host_path}
        type: Directory
service:
  main:
    annotations:
      service.cilium.io/global: "true"
      service.cilium.io/affinity: "local"
ingress:
  main:
    enabled: false
