apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: internal-dns--client-lookup
  namespace: flux-systems
spec:
  releaseName: client-lookup
  interval: 5m
  targetNamespace: internal-dns
  valuesFrom:
  - kind: ConfigMap
    name: client-lookup-values
    valuesKey: values-base.yaml
  - kind: ConfigMap
    name: client-lookup-values
    optional: true
    valuesKey: values-shared.yaml
  - kind: ConfigMap
    name: client-lookup-values
    optional: true
    valuesKey: values.yaml
