apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- httproute.yaml
- networkpolicy.yaml
- imagerepository.yaml
- imagepolicy.yaml
configMapGenerator:
- name: vpn-gateway-client
  namespace: vpn-gateway
  files:
  - settings.sh=config/settings.sh
  - nat.conf=config/nat.conf
  options:
    disableNameSuffixHash: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default"
