apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-gateway-state
  namespace: vpn-gateway
  labels:
    app.kubernetes.io/name: vpn-gateway
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: topolvm-default
  resources:
    requests:
      storage: 1Gi
