apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr
  namespace: default
spec:
  parentRefs:
  - name: envoy-gw
    namespace: envoy-gateway-system
  - name: envoy-gw-private
    namespace: envoy-gateway-system
    sectionName: wahooli-https
  hostnames:
  - "sonarr.${domain_wahoo_li:=wahoo.li}"
  rules:
  # API — extended timeout
  - backendRefs:
    - name: ak-outpost-nasse-proxy
      port: 9000
    matches:
    - path:
        type: PathPrefix
        value: /api
    timeouts:
      request: 900s
      backendRequest: 900s
  # Everything else — default
  - backendRefs:
    - name: ak-outpost-nasse-proxy
      port: 9000
