apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-config
  namespace: default
  labels:
    app.kubernetes.io/name: jdownloader
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: topolvm-default
  resources:
    requests:
      storage: 2Gi
