apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-backup-filer-lb
  namespace: seaweedfs-backup
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "remote"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: s3
    port: 8333
    protocol: TCP
    targetPort: 8333
  type: ClusterIP
