name: End to end test

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Comma-separated list of directories to run reconcile against'
        default: 'vm'
        required: true
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  push:
    branches:
    - '*'
    - '!flux-image-updates'
    - '!flux-system-update'
    tags-ignore:
    - '*'
    paths-ignore:
    - 'charts/**'
    - 'inventory/**'
    - 'githooks/**'
    - '*.md'
    - 'LICENSE'

jobs:
  lint:
    name: Lint YAML and get modified helmreleases
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.helmreleases.outputs.test_matrix || steps.clusters.outputs.test_matrix }}
    steps:
    - name: Install git, yamllint, wget, curl and yq
      if: runner.environment == 'self-hosted'
      run: |
        sudo apt-get update -qqy
        sudo apt-get install git yamllint curl wget -qqy --no-install-recommends
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod a+x /usr/bin/yq
    - name: Setup Flux
      if: github.event_name != 'workflow_dispatch'
      uses: fluxcd/flux2/action@main
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: 🚀 Run yamllint
      run: |
        yamllint -s -c .yamllint .
    - name: Get changed directories
      id: changed-directories
      if: github.event_name != 'workflow_dispatch'
      uses: tj-actions/changed-files@v46.0.5
      with:
        dir_names_exclude_current_dir: true
        files: |
          apps/**/*
          infrastructure/**/*
          clusters/**/*
        files_ignore: |
          *.md
          **/ci-excluded/**
          apps/.config/*
    - name: Get changed helmreleases
      if: github.event_name != 'workflow_dispatch'
      id: helmreleases
      env:
        FILES: "${{ steps.changed-directories.outputs.all_changed_files }}"
      run: scripts/ci/get-changed-helmreleases.sh
    - name: Define test matrix
      if: github.event_name == 'workflow_dispatch'
      id: clusters
      run: |
        scripts/ci/parse-workflow-dispatch-input.sh "${{ inputs.cluster }}"

  kubernetes:
    runs-on: ubuntu-latest
    needs: lint
    name: Test flux reconciliation for ${{ matrix.test.tenant }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.lint.outputs.matrix ) }}
    if: ${{ needs.lint.outputs.matrix != '[]' && needs.lint.outputs.matrix != '' }}
    steps:
    - name: Get more disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: false
        docker-images: false
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        sparse-checkout: |
          scripts/ci/
          .github/workflows
          apps
          crds
          clusters
          infrastructure
          local-clusters
          scripts
          .sourceignore
    - name: Install required self-hosted dependencies
      if: runner.environment == 'self-hosted'
      run: |
        sudo apt-get update -qqy
        sudo apt-get install git curl wget jq openssl -qqy --no-install-recommends
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/bin/yq
    - name: Install tools
      if: runner.environment != 'self-hosted'
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/bin/yq
    - name: Setup Flux
      uses: fluxcd/flux2/action@main
      with:
        version: '${{ matrix.test.flux_version }}'
    - name: Create k3d cluster
      env:
        K3D_SERVERS: "1"
        K3D_AGENTS: "0"
      run: scripts/create-cluster.sh ${{ matrix.test.tenant }}
    - name: Patch manifests for CI
      run: scripts/ci/patch-manifests.sh
    - name: Bootstrap Flux
      run: scripts/bootstrap-flux.sh ${{ matrix.test.tenant }}
    - name: Verify kustomization reconciliation
      env:
        TENANT: "${{ matrix.test.tenant }}"
        CONTEXT: "k3d-${{ matrix.test.tenant }}"
      run: scripts/verify-kustomizations.sh
    - name: Suspend all HelmReleases
      env:
        CONTEXT: "k3d-${{ matrix.test.tenant }}"
      run: flux suspend helmrelease --all -n flux-system --context "$CONTEXT"
    - name: Verify helmrelease reconciliation
      id: helmrelease-verify
      env:
        HELM_RELEASES: "${{ join(matrix.test.helmreleases, ',') }}"
        TENANT: "${{ matrix.test.tenant }}"
        CONTEXT: "k3d-${{ matrix.test.tenant }}"
      run: scripts/verify-helmreleases.sh
    - name: Debug failure
      if: failure()
      env:
        DEBUG_LOGS: "true"
        HELM_RELEASES: "${{ steps.helmrelease-verify.outputs.failing_helmrelease || join(matrix.test.helmreleases, ',') }}"
      run: scripts/ci/debug-failure.sh
